In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
!nvidia-smi

Sun Apr 19 19:08:38 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.105.08             Driver Version: 580.105.08     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA L40S                    On  |   00000000:4A:00.0 Off |                    0 |
| N/A   28C    P8             33W /  350W |       0MiB /  46068MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [3]:
# Put project root on sys.path so "source" is importable
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().resolve().parent  # notebooks/ -> root/
PROJECT_ROOT = PROJECT_ROOT #/ "lcms-foundation-model"
print(PROJECT_ROOT)
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

/home/mpominova/lcms-foundation-model

In [4]:
import os
import yaml
import numpy as np
import pandas as pd
import polars as pl

import torch
import torch.nn as nn
import pytorch_lightning as L
from tqdm import tqdm
from depthcharge.data import SpectrumDataset, spectra_to_df, preprocessing
from torch.utils.data import DataLoader

from source.dataset import LanceMapDataset, RunDataset
from source.model import MS1Encoder
from source.scheduler import CosineWarmupScheduler
from source.config import ExperimentConfig, DataConfig, ModelConfig, OptimizerConfig, TrainingConfig

/home/mpominova/.local/share/mamba/envs/lcms-foundation/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [5]:
# we might want to add this to the MS1Encoder for some debugging / control
# but later / optional

# # Display prediction sample
# n = 30
# mz_bins_true, I_true = target_mz_bins[:n].cpu().numpy(), target_I[:n].cpu().numpy()
# mz_bins_pred, I_pred = pred_mz_bins[:n].argmax(dim=1).cpu().numpy(), pred_I[:n].cpu().numpy()
# sample_df = np.column_stack((
#     mz_bins_true.ravel(), 
#     I_true.ravel(), 
#     mz_bins_pred.ravel(), 
#     # I_pred.ravel()
# ))
# sample_df = pd.DataFrame(
#     sample_df, columns=[
#         "mz_bins_true", 
#         "I_true", 
#         "mz_bins_pred", 
#         # "I_pred"
#     ]
# )
# display(sample_df)

In [6]:
def load_config(config_path):
    """Load configuration from YAML file."""
    with open(config_path, "r") as f:
        config_dict = yaml.safe_load(f)
        config = ExperimentConfig(
            name=config_dict['name'],
            data=DataConfig(**config_dict['data']),
            model=ModelConfig(**config_dict['model']),
            optimizer=OptimizerConfig(**config_dict['optimizer']),
            training=TrainingConfig(**config_dict['training'])
        )
    return config

In [7]:
# Load training data
data_root_dir = "/mnt/data/shared/lc_ms_foundation/"
# data_root_dir = "/mnt/data/shared/lc_ms_foundation/"
dset_name = "abele_data"
data_dir = os.path.join(data_root_dir, dset_name, "mzml")

mzml_files = os.listdir(data_dir)
print("Total N files:", len(mzml_files))

Total N files: 1334

In [8]:
selected_genuses = [
    "Pseudomonas", 
    # "Staphylococcus", 
    "Bacillus", 
    "Escherichia", 
    "Enterococcus",
    "Lactococcus",
    # "Serratia",
    # "Acinetobacter",
]

In [9]:
meta_df = pl.read_csv(os.path.join(
    data_root_dir, 
    dset_name,
    "all_abele_metadata.csv"
))

meta_df = meta_df.rename({
    "characteristics[organism]": "organism",
    "comment[data file]": "data_file"
})

meta_df = meta_df.filter(meta_df["genus"].is_in(selected_genuses))
meta_df

shape: (535, 3)
┌─────────────────────────┬─────────────┬─────────────────────────┐
│ organism                ┆ genus       ┆ data_file               │
│ ---                     ┆ ---         ┆ ---                     │
│ str                     ┆ str         ┆ str                     │
╞═════════════════════════╪═════════════╪═════════════════════════╡
│ Bacillus cereus         ┆ Bacillus    ┆ BBM_429_P110_31_MIA_007 │
│ Pseudomonas aeruginosa  ┆ Pseudomonas ┆ BBM_437_P110_31_MIA_036 │
│ Bacillus pumilus        ┆ Bacillus    ┆ BBM_429_P110_31_MIA_023 │
│ Bacillus subtilis       ┆ Bacillus    ┆ BBM_429_P110_31_MIA_024 │
│ Pseudomonas fluorescens ┆ Pseudomonas ┆ BBM_441_P110_31_MIA_015 │
│ …                       ┆ …           ┆ …                       │
│ Escherichia coli        ┆ Escherichia ┆ BBM_749_P110_38_MIA_095 │
│ Escherichia coli        ┆ Escherichia ┆ BBM_749_P110_38_MIA_096 │
│ Pseudomonas aeruginosa  ┆ Pseudomonas ┆ BBM_750_P110_38_MIA_001 │
│ Pseudomonas aeruginosa  ┆ Pseudomonas ┆ BBM_750_P110_38_MIA_002 │
│ Pseudomonas aeruginosa  ┆ Pseudomonas ┆ BBM_750_P110_38_MIA_003 │
└─────────────────────────┴─────────────┴─────────────────────────┘

In [10]:
meta_df["genus"].value_counts()

shape: (5, 2)
┌──────────────┬───────┐
│ genus        ┆ count │
│ ---          ┆ ---   │
│ str          ┆ u32   │
╞══════════════╪═══════╡
│ Enterococcus ┆ 42    │
│ Bacillus     ┆ 109   │
│ Lactococcus  ┆ 21    │
│ Escherichia  ┆ 51    │
│ Pseudomonas  ┆ 312   │
└──────────────┴───────┘

In [11]:
# Pseudomonas, Bacillus, Escherichia are used for petraining
# and Enterococcus and Lactococcus are split between train and val for downstream eval
# - group by organism, put all files of the same organism in one split

In [12]:
# Use our "default" parameters from config to load data

# TODO: do we maybe need separate configs for different types of experiments?
# (e.g. MS2, MS1, online eval, retrain eval, run, ... ?)
# TODO: would be nice to fix some convenient naming convention for experiments

# config = load_config("../config.yaml")
config = load_config(PROJECT_ROOT / "config.yaml")
config

ExperimentConfig(name='ms1-mz-200_peaks-sqrt-clf_run_retrain', data=DataConfig(train_dir='train_mzml', val_dir='val_mzml', batch_size=1000, max_num_peaks=200), model=ModelConfig(d_model=256, nhead=8, dim_feedforward=512, n_layers=6, dropout=0.1, n_bins=1200, bin_mz_min=300, bin_mz_max=1500, masked_peaks_fraction=0.3), optimizer=OptimizerConfig(lr=0.0005, warmup_iters=1000, cosine_schedule_period_iters=64000), training=TrainingConfig(checkpoint_path='./train_checkpoints', max_epochs=1000, gradient_clip_val=5, accelerator='gpu', devices=1))

In [13]:
meta_df["genus"].value_counts()

shape: (5, 2)
┌──────────────┬───────┐
│ genus        ┆ count │
│ ---          ┆ ---   │
│ str          ┆ u32   │
╞══════════════╪═══════╡
│ Bacillus     ┆ 109   │
│ Pseudomonas  ┆ 312   │
│ Enterococcus ┆ 42    │
│ Escherichia  ┆ 51    │
│ Lactococcus  ┆ 21    │
└──────────────┴───────┘

In [14]:
genus_class = {
    "Enterococcus": 0,
    "Lactococcus": 1,
    #
    "Pseudomonas": 2,
    "Bacillus": 3,
    "Escherichia": 4,
}
meta_df = meta_df.with_columns((pl.col("data_file") + ".mzML").alias("peak_file"))
meta_df = meta_df.with_columns(
    (pl.col("genus").replace(genus_class, return_dtype=int).alias("genus_class"))
)

display(meta_df["genus_class"].value_counts())
meta_df

/tmp/ipykernel_41649/2649999018.py:11: DeprecationWarning: the `return_dtype` parameter for `replace` is deprecated. Use `replace_strict` instead to set a return data type while replacing values.
(Deprecated in version 1.0.0)
  (pl.col("genus").replace(genus_class, return_dtype=int).alias("genus_class"))

shape: (5, 2)
┌─────────────┬───────┐
│ genus_class ┆ count │
│ ---         ┆ ---   │
│ i64         ┆ u32   │
╞═════════════╪═══════╡
│ 1           ┆ 21    │
│ 2           ┆ 312   │
│ 0           ┆ 42    │
│ 3           ┆ 109   │
│ 4           ┆ 51    │
└─────────────┴───────┘

shape: (535, 5)
┌───────────────────┬─────────────┬─────────────────────────┬────────────────────────┬─────────────┐
│ organism          ┆ genus       ┆ data_file               ┆ peak_file              ┆ genus_class │
│ ---               ┆ ---         ┆ ---                     ┆ ---                    ┆ ---         │
│ str               ┆ str         ┆ str                     ┆ str                    ┆ i64         │
╞═══════════════════╪═════════════╪═════════════════════════╪════════════════════════╪═════════════╡
│ Bacillus cereus   ┆ Bacillus    ┆ BBM_429_P110_31_MIA_007 ┆ BBM_429_P110_31_MIA_00 ┆ 3           │
│                   ┆             ┆                         ┆ 7.mzML                 ┆             │
│ Pseudomonas       ┆ Pseudomonas ┆ BBM_437_P110_31_MIA_036 ┆ BBM_437_P110_31_MIA_03 ┆ 2           │
│ aeruginosa        ┆             ┆                         ┆ 6.mzML                 ┆             │
│ Bacillus pumilus  ┆ Bacillus    ┆ BBM_429_P110_31_MIA_023 ┆ BBM_429_P110_31_MIA_02 ┆ 3           │
│                   ┆             ┆                         ┆ 3.mzML                 ┆             │
│ Bacillus subtilis ┆ Bacillus    ┆ BBM_429_P110_31_MIA_024 ┆ BBM_429_P110_31_MIA_02 ┆ 3           │
│                   ┆             ┆                         ┆ 4.mzML                 ┆             │
│ Pseudomonas       ┆ Pseudomonas ┆ BBM_441_P110_31_MIA_015 ┆ BBM_441_P110_31_MIA_01 ┆ 2           │
│ fluorescens       ┆             ┆                         ┆ 5.mzML                 ┆             │
│ …                 ┆ …           ┆ …                       ┆ …                      ┆ …           │
│ Escherichia coli  ┆ Escherichia ┆ BBM_749_P110_38_MIA_095 ┆ BBM_749_P110_38_MIA_09 ┆ 4           │
│                   ┆             ┆                         ┆ 5.mzML                 ┆             │
│ Escherichia coli  ┆ Escherichia ┆ BBM_749_P110_38_MIA_096 ┆ BBM_749_P110_38_MIA_09 ┆ 4           │
│                   ┆             ┆                         ┆ 6.mzML                 ┆             │
│ Pseudomonas       ┆ Pseudomonas ┆ BBM_750_P110_38_MIA_001 ┆ BBM_750_P110_38_MIA_00 ┆ 2           │
│ aeruginosa        ┆             ┆                         ┆ 1.mzML                 ┆             │
│ Pseudomonas       ┆ Pseudomonas ┆ BBM_750_P110_38_MIA_002 ┆ BBM_750_P110_38_MIA_00 ┆ 2           │
│ aeruginosa        ┆             ┆                         ┆ 2.mzML                 ┆             │
│ Pseudomonas       ┆ Pseudomonas ┆ BBM_750_P110_38_MIA_003 ┆ BBM_750_P110_38_MIA_00 ┆ 2           │
│ aeruginosa        ┆             ┆                         ┆ 3.mzML                 ┆             │
└───────────────────┴─────────────┴─────────────────────────┴────────────────────────┴─────────────┘

In [15]:
# data_dir = "/mnt/data/mpominova/lcms_foundation_data/abele_data"
data_dir = "/mnt/data2/mpominova/lcms_foundation_data/abele_data"
len(os.listdir(data_dir)), os.listdir(data_dir)[:2]

(722, ['BBM_429_P110_31_MIA_026.parquet', 'BBM_429_P110_31_MIA_007.parquet'])

In [16]:
mzml_files = [
    f + ".parquet" for f in meta_df["data_file"].to_list()
    if f + ".parquet" in os.listdir(data_dir)
]
len(mzml_files), mzml_files[:5]

(535,
 ['BBM_429_P110_31_MIA_007.parquet',
  'BBM_437_P110_31_MIA_036.parquet',
  'BBM_429_P110_31_MIA_023.parquet',
  'BBM_429_P110_31_MIA_024.parquet',
  'BBM_441_P110_31_MIA_015.parquet'])

In [17]:
# how do we load only the files we need for the selected genuses?
dfs = {
    mzml_file: pl.read_parquet(os.path.join(data_dir, mzml_file))
    for mzml_file in tqdm(mzml_files)
}
len(dfs)

100%|██████████| 535/535 [00:19<00:00, 27.84it/s]

535

In [18]:
train_genuses = ['Pseudomonas', 'Bacillus', 'Escherichia']
probe_genuses = ["Enterococcus", "Lactococcus"]

In [19]:
g = meta_df.select(["organism", "genus_class"]).group_by("organism")
sorted_organisms = g.first().sort(by=["genus_class", "organism"])["genus_class", "organism"]
sorted_organisms

shape: (74, 2)
┌─────────────┬────────────────────────────┐
│ genus_class ┆ organism                   │
│ ---         ┆ ---                        │
│ i64         ┆ str                        │
╞═════════════╪════════════════════════════╡
│ 0           ┆ Enterococcus avium         │
│ 0           ┆ Enterococcus casseliflavus │
│ 0           ┆ Enterococcus cecorum       │
│ 0           ┆ Enterococcus columbae      │
│ 0           ┆ Enterococcus dispar        │
│ …           ┆ …                          │
│ 3           ┆ Bacillus sonorensis        │
│ 3           ┆ Bacillus subtilis          │
│ 3           ┆ Bacillus thuringiensis     │
│ 4           ┆ Escherichia coli           │
│ 4           ┆ Escherichia fergusonii     │
└─────────────┴────────────────────────────┘

In [20]:
train_organisms = sorted_organisms.filter(
    sorted_organisms["genus_class"] >= 2
)["organism"].to_list()

val_organisms = sorted_organisms.filter(
    sorted_organisms["genus_class"].is_in([0, 1])
)["organism"].to_list()

probe_train_organisms = val_organisms[::2]
probe_val_organisms = [
    organism for organism in val_organisms 
    if organism not in probe_train_organisms
]

len(train_organisms), len(probe_train_organisms), len(probe_val_organisms)

(54, 10, 10)

In [21]:
meta_df.filter(
    meta_df["organism"].is_in(probe_train_organisms)
)["genus"].value_counts().sort(by="genus")

shape: (2, 2)
┌──────────────┬───────┐
│ genus        ┆ count │
│ ---          ┆ ---   │
│ str          ┆ u32   │
╞══════════════╪═══════╡
│ Enterococcus ┆ 21    │
│ Lactococcus  ┆ 12    │
└──────────────┴───────┘

In [22]:
meta_df.filter(
    meta_df["organism"].is_in(probe_val_organisms)
)["genus"].value_counts().sort(by="genus")

shape: (2, 2)
┌──────────────┬───────┐
│ genus        ┆ count │
│ ---          ┆ ---   │
│ str          ┆ u32   │
╞══════════════╪═══════╡
│ Enterococcus ┆ 21    │
│ Lactococcus  ┆ 9     │
└──────────────┴───────┘

In [23]:
display(sorted_organisms.filter(
    sorted_organisms["organism"].is_in(probe_train_organisms)
))
display(sorted_organisms.filter(
    sorted_organisms["organism"].is_in(probe_val_organisms)
))

shape: (10, 2)
┌─────────────┬──────────────────────────────┐
│ genus_class ┆ organism                     │
│ ---         ┆ ---                          │
│ i64         ┆ str                          │
╞═════════════╪══════════════════════════════╡
│ 0           ┆ Enterococcus avium           │
│ 0           ┆ Enterococcus cecorum         │
│ 0           ┆ Enterococcus dispar          │
│ 0           ┆ Enterococcus faecalis        │
│ 0           ┆ Enterococcus hirae           │
│ 0           ┆ Enterococcus mundtii         │
│ 0           ┆ Enterococcus saccharolyticus │
│ 1           ┆ Lactococcus cremoris         │
│ 1           ┆ Lactococcus lactis           │
│ 1           ┆ Lactococcus plantarum        │
└─────────────┴──────────────────────────────┘

shape: (10, 2)
┌─────────────┬────────────────────────────┐
│ genus_class ┆ organism                   │
│ ---         ┆ ---                        │
│ i64         ┆ str                        │
╞═════════════╪════════════════════════════╡
│ 0           ┆ Enterococcus casseliflavus │
│ 0           ┆ Enterococcus columbae      │
│ 0           ┆ Enterococcus durans        │
│ 0           ┆ Enterococcus faecium       │
│ 0           ┆ Enterococcus malodoratus   │
│ 0           ┆ Enterococcus raffinosus    │
│ 0           ┆ Enterococcus sulfureus     │
│ 1           ┆ Lactococcus garvieae       │
│ 1           ┆ Lactococcus piscium        │
│ 1           ┆ Lactococcus raffinolactis  │
└─────────────┴────────────────────────────┘

In [24]:
organism2split = {}
for organism in train_organisms:
    organism2split[organism] = "train"
for organism in probe_train_organisms:
    organism2split[organism] = "probe_train"
for organism in probe_val_organisms:
    organism2split[organism] = "probe_val"
    
meta_df = meta_df.with_columns(
    pl.col("organism").replace(organism2split).alias("split")
)
meta_df

shape: (535, 6)
┌────────────────────┬─────────────┬────────────────────┬────────────────────┬─────────────┬───────┐
│ organism           ┆ genus       ┆ data_file          ┆ peak_file          ┆ genus_class ┆ split │
│ ---                ┆ ---         ┆ ---                ┆ ---                ┆ ---         ┆ ---   │
│ str                ┆ str         ┆ str                ┆ str                ┆ i64         ┆ str   │
╞════════════════════╪═════════════╪════════════════════╪════════════════════╪═════════════╪═══════╡
│ Bacillus cereus    ┆ Bacillus    ┆ BBM_429_P110_31_MI ┆ BBM_429_P110_31_MI ┆ 3           ┆ train │
│                    ┆             ┆ A_007              ┆ A_007.mzML         ┆             ┆       │
│ Pseudomonas        ┆ Pseudomonas ┆ BBM_437_P110_31_MI ┆ BBM_437_P110_31_MI ┆ 2           ┆ train │
│ aeruginosa         ┆             ┆ A_036              ┆ A_036.mzML         ┆             ┆       │
│ Bacillus pumilus   ┆ Bacillus    ┆ BBM_429_P110_31_MI ┆ BBM_429_P110_31_MI ┆ 3           ┆ train │
│                    ┆             ┆ A_023              ┆ A_023.mzML         ┆             ┆       │
│ Bacillus subtilis  ┆ Bacillus    ┆ BBM_429_P110_31_MI ┆ BBM_429_P110_31_MI ┆ 3           ┆ train │
│                    ┆             ┆ A_024              ┆ A_024.mzML         ┆             ┆       │
│ Pseudomonas        ┆ Pseudomonas ┆ BBM_441_P110_31_MI ┆ BBM_441_P110_31_MI ┆ 2           ┆ train │
│ fluorescens        ┆             ┆ A_015              ┆ A_015.mzML         ┆             ┆       │
│ …                  ┆ …           ┆ …                  ┆ …                  ┆ …           ┆ …     │
│ Escherichia coli   ┆ Escherichia ┆ BBM_749_P110_38_MI ┆ BBM_749_P110_38_MI ┆ 4           ┆ train │
│                    ┆             ┆ A_095              ┆ A_095.mzML         ┆             ┆       │
│ Escherichia coli   ┆ Escherichia ┆ BBM_749_P110_38_MI ┆ BBM_749_P110_38_MI ┆ 4           ┆ train │
│                    ┆             ┆ A_096              ┆ A_096.mzML         ┆             ┆       │
│ Pseudomonas        ┆ Pseudomonas ┆ BBM_750_P110_38_MI ┆ BBM_750_P110_38_MI ┆ 2           ┆ train │
│ aeruginosa         ┆             ┆ A_001              ┆ A_001.mzML         ┆             ┆       │
│ Pseudomonas        ┆ Pseudomonas ┆ BBM_750_P110_38_MI ┆ BBM_750_P110_38_MI ┆ 2           ┆ train │
│ aeruginosa         ┆             ┆ A_002              ┆ A_002.mzML         ┆             ┆       │
│ Pseudomonas        ┆ Pseudomonas ┆ BBM_750_P110_38_MI ┆ BBM_750_P110_38_MI ┆ 2           ┆ train │
│ aeruginosa         ┆             ┆ A_003              ┆ A_003.mzML         ┆             ┆       │
└────────────────────┴─────────────┴────────────────────┴────────────────────┴─────────────┴───────┘

In [25]:
# Data for SSL training
split_df = meta_df.filter(pl.col("split") == "train")
print("SSL train - Total:", len(split_df))
display(split_df["genus_class"].value_counts(normalize=False).sort(by="genus_class"))
# display(split_df["genus_class"].value_counts(normalize=True).sort(by="genus_class"))

# Data for downstream model training
split_df = meta_df.filter(pl.col("split") == "probe_train")
print("Downstream train - Total:", len(split_df))
display(split_df["genus_class"].value_counts(normalize=False).sort(by="genus_class"))
# display(split_df["genus_class"].value_counts(normalize=True).sort(by="genus_class"))

# Data for downstream model validation
split_df = meta_df.filter(pl.col("split") == "probe_val")
print("Downstream val - Total:", len(split_df))
display(split_df["genus_class"].value_counts(normalize=False).sort(by="genus_class"))
# display(split_df["genus_class"].value_counts(normalize=True).sort(by="genus_class"))

SSL train - Total: 472

shape: (3, 2)
┌─────────────┬───────┐
│ genus_class ┆ count │
│ ---         ┆ ---   │
│ i64         ┆ u32   │
╞═════════════╪═══════╡
│ 2           ┆ 312   │
│ 3           ┆ 109   │
│ 4           ┆ 51    │
└─────────────┴───────┘

Downstream train - Total: 33

shape: (2, 2)
┌─────────────┬───────┐
│ genus_class ┆ count │
│ ---         ┆ ---   │
│ i64         ┆ u32   │
╞═════════════╪═══════╡
│ 0           ┆ 21    │
│ 1           ┆ 12    │
└─────────────┴───────┘

Downstream val - Total: 30

shape: (2, 2)
┌─────────────┬───────┐
│ genus_class ┆ count │
│ ---         ┆ ---   │
│ i64         ┆ u32   │
╞═════════════╪═══════╡
│ 0           ┆ 21    │
│ 1           ┆ 9     │
└─────────────┴───────┘

In [26]:
# train SpectrumDataset
train_df = pl.concat(
    [
        dfs[mzml_file.replace("mzML", "parquet")] for mzml_file 
        in meta_df.filter(pl.col("split") == "train")["peak_file"].to_list()
    ], 
    how="vertical"
)
train_df = train_df.join(meta_df, on="peak_file", how="left")

# val SpectrumDataset
val_df = pl.concat(
    [
        dfs[mzml_file.replace("mzML", "parquet")] for mzml_file 
        in meta_df.filter(
            pl.col("split").is_in(["probe_train", "probe_val"])
        )["peak_file"].to_list()
    ], 
    how="vertical"
)
val_df = val_df.join(meta_df, on="peak_file", how="left")

train_df.shape, val_df.shape

((1194023, 8), (207979, 8))

In [27]:
# we had 1734898 train MS1 spectra before (with Staphylococcus)
# so we might want to add some more data of Pseudomonadota if this performs worse

In [28]:
train_stream = SpectrumDataset(
    train_df.select(["mz_array", "intensity_array", "genus_class"]), 
    batch_size=256, # streaming batch size, not training batch size
)
print("N train spectra", train_stream.n_spectra)
train_lance_path = str(train_stream.path)   # this is the key
print("Lance dataset path:", train_lance_path)
train_dataset = LanceMapDataset(train_lance_path, seq_len=config.data.max_num_peaks)

val_stream = SpectrumDataset(
    val_df.select(["mz_array", "intensity_array", "genus_class"]), 
    batch_size=256, # streaming batch size, not training batch size
)
print("N train spectra", val_stream.n_spectra)
val_lance_path = str(val_stream.path)   # this is the key
print("Lance dataset path:", val_lance_path)
val_dataset = LanceMapDataset(val_lance_path, seq_len=config.data.max_num_peaks)

N train spectra 1194023
Lance dataset path: /tmp/tmpsnmdoy4i/5c722a3d-469f-47cd-814f-e9e526665208.lance
N train spectra 207979
Lance dataset path: /tmp/tmpvwqavycr/b76fcb0e-8b61-4c5d-bcf1-8a136a353de1.lance

In [29]:
run_labels = dict(zip(meta_df["peak_file"], meta_df["genus_class"]))

probe_train_dataset = RunDataset(
    [
        dfs[mzml_file.replace("mzML", "parquet")] for mzml_file 
        in meta_df.filter(pl.col("split") == "probe_train")["peak_file"].to_list()
    ], 
    run_labels=run_labels, 
    seq_len=config.data.max_num_peaks
)
probe_val_dataset = RunDataset(
    [
        dfs[mzml_file.replace("mzML", "parquet")] for mzml_file 
        in meta_df.filter(pl.col("split") == "probe_val")["peak_file"].to_list()
    ], 
    run_labels=run_labels,
    seq_len=config.data.max_num_peaks
)
len(probe_train_dataset), len(probe_val_dataset)

100%|██████████| 33/33 [00:00<00:00, 86.60it/s]
100%|██████████| 30/30 [00:00<00:00, 90.36it/s]

(33, 30)

In [30]:
def run_collate_fn(rows):
    # rows is a list of dicts, one per spectrum
    keys = rows[0].keys()
    batch = {}
    for key in keys:
        if key in ['mz_array', 'intensity_array']:
            batch[key] = [torch.tensor(r[key]) for r in rows]
        else:
            batch[key] = torch.tensor([r[key] for r in rows])
    return batch

In [31]:
BATCH_SIZE = config.data.batch_size

train_loader = DataLoader(
    train_dataset, 
    batch_size=BATCH_SIZE, 
    num_workers=0, 
    shuffle=True
)
val_loader = DataLoader(
    val_dataset, 
    batch_size=BATCH_SIZE, 
    num_workers=0, 
    shuffle=False
)
print("SSL n batches (MS1-level):", len(train_loader), len(val_loader))

probe_train_loader = DataLoader(
    probe_train_dataset, 
    batch_size=BATCH_SIZE, 
    num_workers=0, 
    shuffle=True,
    collate_fn=run_collate_fn,
)
probe_val_loader = DataLoader(
    probe_val_dataset, 
    batch_size=BATCH_SIZE, 
    num_workers=0, 
    shuffle=False,
    collate_fn=run_collate_fn,
)
print("Downstream n batches (run-level):", len(probe_train_loader), len(probe_val_loader))

SSL n batches (MS1-level): 1195 208
Downstream n batches (run-level): 1 1

In [32]:
# before we used FineTuner callback right here
# but now we would want to import it from  eval/callback.py, right? 
# (I don't know whether eval/ should live inside source/ as well)

from eval.callbacks import FineTuner

In [33]:
config

ExperimentConfig(name='ms1-mz-200_peaks-sqrt-clf_run_retrain', data=DataConfig(train_dir='train_mzml', val_dir='val_mzml', batch_size=1000, max_num_peaks=200), model=ModelConfig(d_model=256, nhead=8, dim_feedforward=512, n_layers=6, dropout=0.1, n_bins=1200, bin_mz_min=300, bin_mz_max=1500, masked_peaks_fraction=0.3), optimizer=OptimizerConfig(lr=0.0005, warmup_iters=1000, cosine_schedule_period_iters=64000), training=TrainingConfig(checkpoint_path='./train_checkpoints', max_epochs=1000, gradient_clip_val=5, accelerator='gpu', devices=1))

In [34]:
model = MS1Encoder(
    d_model=config.model.d_model,
    nhead=config.model.nhead,
    dim_feedforward=config.model.dim_feedforward,
    n_layers=config.model.n_layers,
    dropout=config.model.dropout,
    n_bins=config.model.n_bins,
    bin_mz_min=config.model.bin_mz_min,
    bin_mz_max=config.model.bin_mz_max,
    masked_peaks_fraction=config.model.masked_peaks_fraction,
    lr=config.optimizer.lr,
    warmup_iters=config.optimizer.warmup_iters,
    cosine_schedule_period_iters=config.optimizer.cosine_schedule_period_iters,
)

In [35]:
os.path.abspath(config.training.checkpoint_path)

'/home/mpominova/lcms-foundation-model/notebooks/train_checkpoints'

In [36]:
root_dir = os.path.join(config.training.checkpoint_path, "foundation_model")
os.makedirs(root_dir, exist_ok=True)

logger = L.loggers.TensorBoardLogger(
    os.path.join(root_dir, "lightning_logs"),
    name=config.name,
)

In [37]:
# TODO: number of classes needs to be parametrized (based on number of classes in val subset)
# and validation classes need to be "renamed" (mapped) to always be 0 < C < n_classes
meta_df.filter(meta_df["organism"].is_in(val_organisms))["genus_class"].value_counts()

shape: (2, 2)
┌─────────────┬───────┐
│ genus_class ┆ count │
│ ---         ┆ ---   │
│ i64         ┆ u32   │
╞═════════════╪═══════╡
│ 0           ┆ 42    │
│ 1           ┆ 21    │
└─────────────┴───────┘

In [38]:
retrain_finetuner = FineTuner(
    encoder_output_dim=config.model.d_model, 
    num_classes=2,#len(genus_class),
    target_key="label",
    probe_train_loader=probe_train_loader,
    probe_val_loader=probe_val_loader,
    class_weights=None,
    lr=1e-2,
    n_epochs=50,
    min_train_loss=0.2,
)
# checkpoint_callback = L.ModelCheckpoint(every_n_epochs=100, save_top_k=-1, save_last=True)

trainer = L.Trainer(
    logger=logger,
    default_root_dir=root_dir,
    callbacks=[retrain_finetuner], #checkpoint_callback],
    accelerator="gpu", #config.training.accelerator,
    devices=config.training.devices,
    max_epochs=500, #config.training.max_epochs,
    gradient_clip_val=config.training.gradient_clip_val,
    num_sanity_val_steps=2,
    log_every_n_steps=10,
)

/home/mpominova/.local/share/mamba/envs/lcms-foundation/lib/python3.11/site-packages/lightning_fabric/plugins/environments/slurm.py:204: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM, prepend your python command with `srun` like so: srun python /home/mpominova/.local/share/mamba/envs/lcms-foundat ...
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

In [39]:
# Train the model
trainer.fit(
    model, 
    train_loader, 
    val_dataloaders=[val_loader],
    # ckpt_path=ckpt_path, # 
)

You are using a CUDA device ('NVIDIA L40S') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name                  | Type                       | Params | Mode
-----------------------------------------------------------------------------
0 | peak_encoder          | Sequential                 | 131 K  | train
1 | encoder               | SpectrumTransformerEncoder | 3.3 M  | train
2 | head_mz               | Sequential                 | 308 K  | train
3 | loss_mz_bin           | CrossEntropyLoss           | 0      | train
4 | train_accuracy_mz_bin | MulticlassAccuracy         | 0      | train
5 | val_accuracy_mz_bin   | MulticlassAccuracy         | 0      | train
-----------------------------------------------------------------------------
3.6 M     Trainable params
0         Non-trainable params
3.6 M     Total params
14.408    Total estimated model params size (MB)
73        Modules in train mode
0         Modules in eval mode

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/home/mpominova/.local/share/mamba/envs/lcms-foundation/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.

Sanity Checking DataLoader 0:  50%|█████     | 1/2 [00:00<00:00,  2.57it/s]

/home/mpominova/.local/share/mamba/envs/lcms-foundation/lib/python3.11/site-packages/torch/nn/modules/transformer.py:515: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. We recommend specifying layout=torch.jagged when constructing a nested tensor, as this layout receives active development, has better operator coverage, and works with torch.compile. (Triggered internally at /pytorch/aten/src/ATen/NestedTensorImpl.cpp:178.)
  output = torch._nested_tensor_from_mask(

Sanity Checking DataLoader 0: 100%|██████████| 2/2 [00:00<00:00,  2.52it/s]

     targets    prob_0    prob_1
0       1.0  0.664065  0.335935
1       0.0  0.648212  0.351788
2       0.0  0.654831  0.345169
3       0.0  0.654453  0.345547
4       0.0  0.646854  0.353146
5       1.0  0.665036  0.334964
6       1.0  0.656398  0.343602
7       0.0  0.656936  0.343064
8       0.0  0.650239  0.349761
9       0.0  0.652322  0.347678
10      1.0  0.678705  0.321295
11      0.0  0.673834  0.326166
12      0.0  0.679623  0.320377
13      0.0  0.674953  0.325047
14      0.0  0.683153  0.316847
15      1.0  0.677853  0.322147
16      1.0  0.680328  0.319672
17      0.0  0.677684  0.322316
18      0.0  0.677765  0.322235
19      0.0  0.683793  0.316207

/home/mpominova/.local/share/mamba/envs/lcms-foundation/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.

Epoch 0: 100%|██████████| 1195/1195 [16:36<00:00,  1.20it/s, v_num=4, train_acc_mz_bin=0.0435]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation:   0%|          | 0/208 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/208 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 1/208 [00:00<00:24,  8.47it/s]
Validation DataLoader 0:   1%|          | 2/208 [00:00<00:59,  3.45it/s]
Validation DataLoader 0:   1%|▏         | 3/208 [00:01<01:11,  2.88it/s]
Validation DataLoader 0:   2%|▏         | 4/208 [00:01<01:16,  2.68it/s]
Validation DataLoader 0:   2%|▏         | 5/208 [00:01<01:19,  2.55it/s]
Validation DataLoader 0:   3%|▎         | 6/208 [00:02<01:20,  2.50it/s]
Validation DataLoader 0:   3%|▎         | 7/208 [00:02<01:21,  2.47it/s]
Validation DataLoader 0:   4%|▍         | 8/208 [00:03<01:21,  2.46it/s]
Validation DataLoader 0:   4%|▍         | 9/208 [00:03<01:21,  2.45it/s]
Validation DataLoader 0:   5%|▍         | 10/208 [00:04<01:21,  2.44it/s]
Validation DataLoader 0:   5%|▌         | 11/208 [00:04<01:20,  2.44it/s]
Validation DataLoader 0:   6%|▌         | 12/208 [00:04<01:20,  2.43it/s]
Validation DataLoader 0:   6%|▋         | 13/208 [00:05<01:20,  2.42it/s]
Validation DataLoader 0:   7%|▋         | 14/208 [00:05<01:20,  2.42it/s]
Validation DataLoader 0:   7%|▋         | 15/208 [00:06<01:19,  2.42it/s]
Validation DataLoader 0:   8%|▊         | 16/208 [00:06<01:19,  2.42it/s]
Validation DataLoader 0:   8%|▊         | 17/208 [00:07<01:18,  2.42it/s]
Validation DataLoader 0:   9%|▊         | 18/208 [00:07<01:18,  2.42it/s]
Validation DataLoader 0:   9%|▉         | 19/208 [00:07<01:18,  2.41it/s]
Validation DataLoader 0:  10%|▉         | 20/208 [00:08<01:17,  2.41it/s]
Validation DataLoader 0:  10%|█         | 21/208 [00:08<01:17,  2.41it/s]
Validation DataLoader 0:  11%|█         | 22/208 [00:09<01:17,  2.40it/s]
Validation DataLoader 0:  11%|█         | 23/208 [00:09<01:17,  2.40it/s]
Validation DataLoader 0:  12%|█▏        | 24/208 [00:10<01:17,  2.39it/s]
Validation DataLoader 0:  12%|█▏        | 25/208 [00:10<01:16,  2.39it/s]
Validation DataLoader 0:  12%|█▎        | 26/208 [00:10<01:16,  2.39it/s]
Validation DataLoader 0:  13%|█▎        | 27/208 [00:11<01:15,  2.38it/s]
Validation DataLoader 0:  13%|█▎        | 28/208 [00:11<01:15,  2.38it/s]
Validation DataLoader 0:  14%|█▍        | 29/208 [00:12<01:15,  2.37it/s]
Validation DataLoader 0:  14%|█▍        | 30/208 [00:12<01:15,  2.37it/s]
Validation DataLoader 0:  15%|█▍        | 31/208 [00:13<01:14,  2.37it/s]
Validation DataLoader 0:  15%|█▌        | 32/208 [00:13<01:14,  2.37it/s]
Validation DataLoader 0:  16%|█▌        | 33/208 [00:13<01:13,  2.37it/s]
Validation DataLoader 0:  16%|█▋        | 34/208 [00:14<01:13,  2.36it/s]
Validation DataLoader 0:  17%|█▋        | 35/208 [00:14<01:13,  2.36it/s]
Validation DataLoader 0:  17%|█▋        | 36/208 [00:15<01:12,  2.36it/s]
Validation DataLoader 0:  18%|█▊        | 37/208 [00:15<01:12,  2.36it/s]
Validation DataLoader 0:  18%|█▊        | 38/208 [00:16<01:12,  2.36it/s]
Validation DataLoader 0:  19%|█▉        | 39/208 [00:16<01:11,  2.36it/s]
Validation DataLoader 0:  19%|█▉        | 40/208 [00:16<01:11,  2.36it/s]
Validation DataLoader 0:  20%|█▉        | 41/208 [00:17<01:10,  2.35it/s]
Validation DataLoader 0:  20%|██        | 42/208 [00:17<01:10,  2.35it/s]
Validation DataLoader 0:  21%|██        | 43/208 [00:18<01:10,  2.35it/s]
Validation DataLoader 0:  21%|██        | 44/208 [00:18<01:09,  2.35it/s]
Validation DataLoader 0:  22%|██▏       | 45/208 [00:19<01:09,  2.35it/s]
Validation DataLoader 0:  22%|██▏       | 46/208 [00:19<01:09,  2.35it/s]
Validation DataLoader 0:  23%|██▎       | 47/208 [00:20<01:08,  2.34it/s]
Validation DataLoader 0:  23%|██▎       | 48/208 [00:20<01:08,  2.34it/s]
Validation DataLoader 0:  24%|██▎       | 49/208 [00:20<01:07,  2.34it/s]
Validation DataLoader 0:  24%|██▍       | 50/208 [00:21<01:07,  2.34it/s]
Validation DataLoader 0:  25%|██▍       | 51/208 [00:21<01:07,  2.34it/s]
Validation DataLoader 0:  25%|██▌       | 52/208 [00:22<01:06,  2.34it/s]
Validation DataLoader 0:  25%|██▌       | 53/208 [00:22<01:06,  2.34it/s]
Validation DataLoader 0:  26%|██▌       | 54/208 [00:23<01:05,  2.34it/s]
Validation DataLoader 0:  26%|██▋       | 55/208 [00:23<01:05,  2.34it/s]
Validation DataLoader 0:  27%|██▋       | 56/208 [00:23<01:05,  2.34it/s]
Validation DataLoader 0:  27%|██▋       | 57/208 [00:24<01:04,  2.34it/s]
Validation DataLoader 0:  28%|██▊       | 58/208 [00:24<01:04,  2.34it/s]
Validation DataLoader 0:  28%|██▊       | 59/208 [00:25<01:03,  2.33it/s]
Validation DataLoader 0:  29%|██▉       | 60/208 [00:25<01:03,  2.33it/s]
Validation DataLoader 0:  29%|██▉       | 61/208 [00:26<01:03,  2.33it/s]
Validation DataLoader 0:  30%|██▉       | 62/208 [00:26<01:02,  2.32it/s]
Validation DataLoader 0:  30%|███       | 63/208 [00:27<01:02,  2.32it/s]
Validation DataLoader 0:  31%|███       | 64/208 [00:27<01:02,  2.32it/s]
Validation DataLoader 0:  31%|███▏      | 65/208 [00:28<01:02,  2.30it/s]
Validation DataLoader 0:  32%|███▏      | 66/208 [00:28<01:01,  2.30it/s]
Validation DataLoader 0:  32%|███▏      | 67/208 [00:29<01:01,  2.29it/s]
Validation DataLoader 0:  33%|███▎      | 68/208 [00:29<01:01,  2.29it/s]
Validation DataLoader 0:  33%|███▎      | 69/208 [00:30<01:00,  2.29it/s]
Validation DataLoader 0:  34%|███▎      | 70/208 [00:30<01:00,  2.29it/s]
Validation DataLoader 0:  34%|███▍      | 71/208 [00:31<00:59,  2.29it/s]
Validation DataLoader 0:  35%|███▍      | 72/208 [00:31<00:59,  2.29it/s]
Validation DataLoader 0:  35%|███▌      | 73/208 [00:31<00:59,  2.29it/s]
Validation DataLoader 0:  36%|███▌      | 74/208 [00:32<00:58,  2.29it/s]
Validation DataLoader 0:  36%|███▌      | 75/208 [00:32<00:58,  2.28it/s]
Validation DataLoader 0:  37%|███▋      | 76/208 [00:33<00:57,  2.28it/s]
Validation DataLoader 0:  37%|███▋      | 77/208 [00:33<00:57,  2.28it/s]
Validation DataLoader 0:  38%|███▊      | 78/208 [00:34<00:56,  2.28it/s]
Validation DataLoader 0:  38%|███▊      | 79/208 [00:34<00:56,  2.28it/s]
Validation DataLoader 0:  38%|███▊      | 80/208 [00:35<00:56,  2.28it/s]
Validation DataLoader 0:  39%|███▉      | 81/208 [00:35<00:55,  2.28it/s]
Validation DataLoader 0:  39%|███▉      | 82/208 [00:35<00:55,  2.28it/s]
Validation DataLoader 0:  40%|███▉      | 83/208 [00:36<00:54,  2.28it/s]
Validation DataLoader 0:  40%|████      | 84/208 [00:36<00:54,  2.28it/s]
Validation DataLoader 0:  41%|████      | 85/208 [00:37<00:54,  2.28it/s]
Validation DataLoader 0:  41%|████▏     | 86/208 [00:37<00:53,  2.27it/s]
Validation DataLoader 0:  42%|████▏     | 87/208 [00:38<00:53,  2.27it/s]
Validation DataLoader 0:  42%|████▏     | 88/208 [00:38<00:52,  2.27it/s]
Validation DataLoader 0:  43%|████▎     | 89/208 [00:39<00:52,  2.27it/s]
Validation DataLoader 0:  43%|████▎     | 90/208 [00:39<00:51,  2.27it/s]
Validation DataLoader 0:  44%|████▍     | 91/208 [00:40<00:51,  2.27it/s]
Validation DataLoader 0:  44%|████▍     | 92/208 [00:40<00:51,  2.27it/s]
Validation DataLoader 0:  45%|████▍     | 93/208 [00:40<00:50,  2.27it/s]
Validation DataLoader 0:  45%|████▌     | 94/208 [00:41<00:50,  2.27it/s]
Validation DataLoader 0:  46%|████▌     | 95/208 [00:41<00:49,  2.27it/s]
Validation DataLoader 0:  46%|████▌     | 96/208 [00:42<00:49,  2.27it/s]
Validation DataLoader 0:  47%|████▋     | 97/208 [00:42<00:48,  2.27it/s]
Validation DataLoader 0:  47%|████▋     | 98/208 [00:43<00:48,  2.27it/s]
Validation DataLoader 0:  48%|████▊     | 99/208 [00:43<00:48,  2.27it/s]
Validation DataLoader 0:  48%|████▊     | 100/208 [00:44<00:47,  2.27it/s]
Validation DataLoader 0:  49%|████▊     | 101/208 [00:44<00:47,  2.27it/s]
Validation DataLoader 0:  49%|████▉     | 102/208 [00:44<00:46,  2.27it/s]
Validation DataLoader 0:  50%|████▉     | 103/208 [00:45<00:46,  2.27it/s]
Validation DataLoader 0:  50%|█████     | 104/208 [00:45<00:45,  2.27it/s]
Validation DataLoader 0:  50%|█████     | 105/208 [00:46<00:45,  2.27it/s]
Validation DataLoader 0:  51%|█████     | 106/208 [00:46<00:44,  2.27it/s]
Validation DataLoader 0:  51%|█████▏    | 107/208 [00:47<00:44,  2.27it/s]
Validation DataLoader 0:  52%|█████▏    | 108/208 [00:47<00:44,  2.27it/s]
Validation DataLoader 0:  52%|█████▏    | 109/208 [00:48<00:43,  2.27it/s]
Validation DataLoader 0:  53%|█████▎    | 110/208 [00:48<00:43,  2.27it/s]
Validation DataLoader 0:  53%|█████▎    | 111/208 [00:48<00:42,  2.27it/s]
Validation DataLoader 0:  54%|█████▍    | 112/208 [00:49<00:42,  2.27it/s]
Validation DataLoader 0:  54%|█████▍    | 113/208 [00:49<00:41,  2.27it/s]
Validation DataLoader 0:  55%|█████▍    | 114/208 [00:50<00:41,  2.27it/s]
Validation DataLoader 0:  55%|█████▌    | 115/208 [00:50<00:41,  2.27it/s]
Validation DataLoader 0:  56%|█████▌    | 116/208 [00:51<00:40,  2.27it/s]
Validation DataLoader 0:  56%|█████▋    | 117/208 [00:51<00:40,  2.27it/s]
Validation DataLoader 0:  57%|█████▋    | 118/208 [00:52<00:39,  2.27it/s]
Validation DataLoader 0:  57%|█████▋    | 119/208 [00:52<00:39,  2.27it/s]
Validation DataLoader 0:  58%|█████▊    | 120/208 [00:52<00:38,  2.27it/s]
Validation DataLoader 0:  58%|█████▊    | 121/208 [00:53<00:38,  2.26it/s]
Validation DataLoader 0:  59%|█████▊    | 122/208 [00:53<00:37,  2.26it/s]
Validation DataLoader 0:  59%|█████▉    | 123/208 [00:54<00:37,  2.26it/s]
Validation DataLoader 0:  60%|█████▉    | 124/208 [00:54<00:37,  2.26it/s]
Validation DataLoader 0:  60%|██████    | 125/208 [00:55<00:36,  2.26it/s]
Validation DataLoader 0:  61%|██████    | 126/208 [00:55<00:36,  2.26it/s]
Validation DataLoader 0:  61%|██████    | 127/208 [00:56<00:35,  2.26it/s]
Validation DataLoader 0:  62%|██████▏   | 128/208 [00:56<00:35,  2.26it/s]
Validation DataLoader 0:  62%|██████▏   | 129/208 [00:57<00:34,  2.26it/s]
Validation DataLoader 0:  62%|██████▎   | 130/208 [00:57<00:34,  2.26it/s]
Validation DataLoader 0:  63%|██████▎   | 131/208 [00:57<00:34,  2.26it/s]
Validation DataLoader 0:  63%|██████▎   | 132/208 [00:58<00:33,  2.26it/s]
Validation DataLoader 0:  64%|██████▍   | 133/208 [00:58<00:33,  2.26it/s]
Validation DataLoader 0:  64%|██████▍   | 134/208 [00:59<00:32,  2.26it/s]
Validation DataLoader 0:  65%|██████▍   | 135/208 [00:59<00:32,  2.26it/s]
Validation DataLoader 0:  65%|██████▌   | 136/208 [01:00<00:31,  2.26it/s]
Validation DataLoader 0:  66%|██████▌   | 137/208 [01:00<00:31,  2.26it/s]
Validation DataLoader 0:  66%|██████▋   | 138/208 [01:00<00:30,  2.26it/s]
Validation DataLoader 0:  67%|██████▋   | 139/208 [01:01<00:30,  2.27it/s]
Validation DataLoader 0:  67%|██████▋   | 140/208 [01:01<00:30,  2.26it/s]
Validation DataLoader 0:  68%|██████▊   | 141/208 [01:02<00:29,  2.26it/s]
Validation DataLoader 0:  68%|██████▊   | 142/208 [01:02<00:29,  2.26it/s]
Validation DataLoader 0:  69%|██████▉   | 143/208 [01:03<00:28,  2.26it/s]
Validation DataLoader 0:  69%|██████▉   | 144/208 [01:03<00:28,  2.26it/s]
Validation DataLoader 0:  70%|██████▉   | 145/208 [01:04<00:27,  2.26it/s]
Validation DataLoader 0:  70%|███████   | 146/208 [01:04<00:27,  2.26it/s]
Validation DataLoader 0:  71%|███████   | 147/208 [01:04<00:26,  2.26it/s]
Validation DataLoader 0:  71%|███████   | 148/208 [01:05<00:26,  2.27it/s]
Validation DataLoader 0:  72%|███████▏  | 149/208 [01:05<00:26,  2.27it/s]
Validation DataLoader 0:  72%|███████▏  | 150/208 [01:06<00:25,  2.27it/s]
Validation DataLoader 0:  73%|███████▎  | 151/208 [01:06<00:25,  2.27it/s]
Validation DataLoader 0:  73%|███████▎  | 152/208 [01:07<00:24,  2.27it/s]
Validation DataLoader 0:  74%|███████▎  | 153/208 [01:07<00:24,  2.27it/s]
Validation DataLoader 0:  74%|███████▍  | 154/208 [01:07<00:23,  2.27it/s]
Validation DataLoader 0:  75%|███████▍  | 155/208 [01:08<00:23,  2.27it/s]
Validation DataLoader 0:  75%|███████▌  | 156/208 [01:08<00:22,  2.27it/s]
Validation DataLoader 0:  75%|███████▌  | 157/208 [01:09<00:22,  2.27it/s]
Validation DataLoader 0:  76%|███████▌  | 158/208 [01:09<00:21,  2.27it/s]
Validation DataLoader 0:  76%|███████▋  | 159/208 [01:09<00:21,  2.27it/s]
Validation DataLoader 0:  77%|███████▋  | 160/208 [01:10<00:21,  2.27it/s]
Validation DataLoader 0:  77%|███████▋  | 161/208 [01:10<00:20,  2.28it/s]
Validation DataLoader 0:  78%|███████▊  | 162/208 [01:11<00:20,  2.28it/s]
Validation DataLoader 0:  78%|███████▊  | 163/208 [01:11<00:19,  2.28it/s]
Validation DataLoader 0:  79%|███████▉  | 164/208 [01:12<00:19,  2.28it/s]
Validation DataLoader 0:  79%|███████▉  | 165/208 [01:12<00:18,  2.28it/s]
Validation DataLoader 0:  80%|███████▉  | 166/208 [01:12<00:18,  2.28it/s]
Validation DataLoader 0:  80%|████████  | 167/208 [01:13<00:18,  2.27it/s]
Validation DataLoader 0:  81%|████████  | 168/208 [01:13<00:17,  2.27it/s]
Validation DataLoader 0:  81%|████████▏ | 169/208 [01:14<00:17,  2.27it/s]
Validation DataLoader 0:  82%|████████▏ | 170/208 [01:14<00:16,  2.27it/s]
Validation DataLoader 0:  82%|████████▏ | 171/208 [01:15<00:16,  2.27it/s]
Validation DataLoader 0:  83%|████████▎ | 172/208 [01:15<00:15,  2.27it/s]
Validation DataLoader 0:  83%|████████▎ | 173/208 [01:16<00:15,  2.27it/s]
Validation DataLoader 0:  84%|████████▎ | 174/208 [01:16<00:14,  2.27it/s]
Validation DataLoader 0:  84%|████████▍ | 175/208 [01:17<00:14,  2.27it/s]
Validation DataLoader 0:  85%|████████▍ | 176/208 [01:17<00:14,  2.27it/s]
Validation DataLoader 0:  85%|████████▌ | 177/208 [01:17<00:13,  2.27it/s]
Validation DataLoader 0:  86%|████████▌ | 178/208 [01:18<00:13,  2.27it/s]
Validation DataLoader 0:  86%|████████▌ | 179/208 [01:18<00:12,  2.27it/s]
Validation DataLoader 0:  87%|████████▋ | 180/208 [01:19<00:12,  2.27it/s]
Validation DataLoader 0:  87%|████████▋ | 181/208 [01:19<00:11,  2.27it/s]
Validation DataLoader 0:  88%|████████▊ | 182/208 [01:20<00:11,  2.27it/s]
Validation DataLoader 0:  88%|████████▊ | 183/208 [01:20<00:11,  2.27it/s]
Validation DataLoader 0:  88%|████████▊ | 184/208 [01:21<00:10,  2.27it/s]
Validation DataLoader 0:  89%|████████▉ | 185/208 [01:21<00:10,  2.27it/s]
Validation DataLoader 0:  89%|████████▉ | 186/208 [01:21<00:09,  2.27it/s]
Validation DataLoader 0:  90%|████████▉ | 187/208 [01:22<00:09,  2.27it/s]
Validation DataLoader 0:  90%|█████████ | 188/208 [01:22<00:08,  2.27it/s]
Validation DataLoader 0:  91%|█████████ | 189/208 [01:23<00:08,  2.27it/s]
Validation DataLoader 0:  91%|█████████▏| 190/208 [01:23<00:07,  2.27it/s]
Validation DataLoader 0:  92%|█████████▏| 191/208 [01:24<00:07,  2.27it/s]
Validation DataLoader 0:  92%|█████████▏| 192/208 [01:24<00:07,  2.27it/s]
Validation DataLoader 0:  93%|█████████▎| 193/208 [01:24<00:06,  2.27it/s]
Validation DataLoader 0:  93%|█████████▎| 194/208 [01:25<00:06,  2.27it/s]
Validation DataLoader 0:  94%|█████████▍| 195/208 [01:25<00:05,  2.27it/s]
Validation DataLoader 0:  94%|█████████▍| 196/208 [01:26<00:05,  2.27it/s]
Validation DataLoader 0:  95%|█████████▍| 197/208 [01:26<00:04,  2.27it/s]
Validation DataLoader 0:  95%|█████████▌| 198/208 [01:27<00:04,  2.27it/s]
Validation DataLoader 0:  96%|█████████▌| 199/208 [01:27<00:03,  2.27it/s]
Validation DataLoader 0:  96%|█████████▌| 200/208 [01:28<00:03,  2.27it/s]
Validation DataLoader 0:  97%|█████████▋| 201/208 [01:28<00:03,  2.27it/s]
Validation DataLoader 0:  97%|█████████▋| 202/208 [01:28<00:02,  2.27it/s]
Validation DataLoader 0:  98%|█████████▊| 203/208 [01:29<00:02,  2.27it/s]
Validation DataLoader 0:  98%|█████████▊| 204/208 [01:29<00:01,  2.27it/s]
Validation DataLoader 0:  99%|█████████▊| 205/208 [01:30<00:01,  2.27it/s]
Validation DataLoader 0:  99%|█████████▉| 206/208 [01:30<00:00,  2.27it/s]
Validation DataLoader 0: 100%|█████████▉| 207/208 [01:31<00:00,  2.27it/s]
Validation DataLoader 0: 100%|██████████| 208/208 [01:31<00:00,  2.27it/s]

     targets    prob_0    prob_1
0       1.0  0.459203  0.540797
1       0.0  0.455485  0.544515
2       0.0  0.466442  0.533558
3       0.0  0.463281  0.536719
4       0.0  0.457454  0.542546
5       1.0  0.490250  0.509750
6       1.0  0.454662  0.545338
7       0.0  0.446124  0.553876
8       0.0  0.457876  0.542124
9       0.0  0.459792  0.540208
10      1.0  0.467498  0.532502
11      0.0  0.482141  0.517859
12      0.0  0.508946  0.491054
13      0.0  0.487722  0.512278
14      0.0  0.528720  0.471280
15      1.0  0.484352  0.515647
16      1.0  0.494695  0.505305
17      0.0  0.482747  0.517253
18      0.0  0.493062  0.506938
19      0.0  0.510673  0.489327



Epoch 0: 100%|██████████| 1195/1195 [18:19<00:00,  1.09it/s, v_num=4, train_acc_mz_bin=0.0435, val_acc_mz_bin=0.0222, retrain_val_auc=0.519, retrain_val_ap=0.551]Probe epoch 0 loss: 0.6979  auc: 0.3889  ap: 0.4479
Probe epoch 1 loss: 0.9330  auc: 0.5159  ap: 0.5787
Probe epoch 2 loss: 0.7028  auc: 0.5952  ap: 0.6327
Probe epoch 3 loss: 0.6732  auc: 0.6508  ap: 0.6832
Probe epoch 4 loss: 0.7591  auc: 0.7103  ap: 0.7289
Probe epoch 5 loss: 0.6674  auc: 0.7460  ap: 0.7655
Probe epoch 6 loss: 0.5953  auc: 0.7579  ap: 0.7730
Probe epoch 7 loss: 0.6214  auc: 0.7897  ap: 0.7956
Probe epoch 8 loss: 0.6428  auc: 0.8651  ap: 0.8560
Probe epoch 9 loss: 0.6082  auc: 0.9325  ap: 0.9163
Probe epoch 10 loss: 0.5540  auc: 0.9484  ap: 0.9432
Probe epoch 11 loss: 0.5377  auc: 0.9484  ap: 0.9509
Probe epoch 12 loss: 0.5575  auc: 0.9405  ap: 0.9403
Probe epoch 13 loss: 0.5546  auc: 0.9444  ap: 0.9434
Probe epoch 14 loss: 0.5189  auc: 0.9563  ap: 0.9576
Probe epoch 15 loss: 0.4910  auc: 0.9683  ap: 0.9677
Probe epoch 16 loss: 0.4907  auc: 0.9563  ap: 0.9511
Probe epoch 17 loss: 0.4962  auc: 0.9603  ap: 0.9552
Probe epoch 18 loss: 0.4858  auc: 0.9563  ap: 0.9511
Probe epoch 19 loss: 0.4631  auc: 0.9563  ap: 0.9511
Probe epoch 20 loss: 0.4463  auc: 0.9603  ap: 0.9552
Probe epoch 21 loss: 0.4444  auc: 0.9683  ap: 0.9665
Probe epoch 22 loss: 0.4454  auc: 0.9722  ap: 0.9701
Probe epoch 23 loss: 0.4354  auc: 0.9683  ap: 0.9660
Probe epoch 24 loss: 0.4188  auc: 0.9683  ap: 0.9660
Probe epoch 25 loss: 0.4085  auc: 0.9722  ap: 0.9701
Probe epoch 26 loss: 0.4066  auc: 0.9762  ap: 0.9751
Probe epoch 27 loss: 0.4043  auc: 0.9722  ap: 0.9710
Probe epoch 28 loss: 0.3959  auc: 0.9722  ap: 0.9710
Probe epoch 29 loss: 0.3847  auc: 0.9683  ap: 0.9677
Probe epoch 30 loss: 0.3773  auc: 0.9683  ap: 0.9677
Probe epoch 31 loss: 0.3747  auc: 0.9683  ap: 0.9677
Probe epoch 32 loss: 0.3715  auc: 0.9722  ap: 0.9710
Probe epoch 33 loss: 0.3642  auc: 0.9683  ap: 0.9677
Probe epoch 34 loss: 0.3559  auc: 0.9722  ap: 0.9710
Probe epoch 35 loss: 0.3506  auc: 0.9802  ap: 0.9791
Probe epoch 36 loss: 0.3478  auc: 0.9802  ap: 0.9791
Probe epoch 37 loss: 0.3441  auc: 0.9841  ap: 0.9838
Probe epoch 38 loss: 0.3381  auc: 0.9841  ap: 0.9838
Probe epoch 39 loss: 0.3320  auc: 0.9841  ap: 0.9838
Probe epoch 40 loss: 0.3277  auc: 0.9921  ap: 0.9918
Probe epoch 41 loss: 0.3247  auc: 0.9921  ap: 0.9918
Probe epoch 42 loss: 0.3209  auc: 0.9921  ap: 0.9918
Probe epoch 43 loss: 0.3159  auc: 0.9921  ap: 0.9918
Probe epoch 44 loss: 0.3111  auc: 0.9921  ap: 0.9918
Probe epoch 45 loss: 0.3075  auc: 0.9921  ap: 0.9918
Probe epoch 46 loss: 0.3046  auc: 0.9921  ap: 0.9918
Probe epoch 47 loss: 0.3009  auc: 0.9921  ap: 0.9918
Probe epoch 48 loss: 0.2967  auc: 0.9921  ap: 0.9918
Probe epoch 49 loss: 0.2928  auc: 0.9921  ap: 0.9918
Epoch 1: 100%|██████████| 1195/1195 [16:41<00:00,  1.19it/s, v_num=4, train_acc_mz_bin=0.0638, val_acc_mz_bin=0.0222, retrain_val_auc=0.519, retrain_val_ap=0.551]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation:   0%|          | 0/208 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/208 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 1/208 [00:00<00:25,  8.20it/s]
Validation DataLoader 0:   1%|          | 2/208 [00:00<00:56,  3.65it/s]
Validation DataLoader 0:   1%|▏         | 3/208 [00:00<01:07,  3.05it/s]
Validation DataLoader 0:   2%|▏         | 4/208 [00:01<01:12,  2.82it/s]
Validation DataLoader 0:   2%|▏         | 5/208 [00:01<01:15,  2.70it/s]
Validation DataLoader 0:   3%|▎         | 6/208 [00:02<01:16,  2.63it/s]

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

Validation:   0%|          | 0/208 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/208 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 1/208 [00:00<00:24,  8.29it/s]
Validation DataLoader 0:   1%|          | 2/208 [00:00<00:54,  3.75it/s]
Validation DataLoader 0:   1%|▏         | 3/208 [00:00<01:05,  3.14it/s]
Validation DataLoader 0:   2%|▏         | 4/208 [00:01<01:10,  2.90it/s]
Validation DataLoader 0:   2%|▏         | 5/208 [00:01<01:13,  2.78it/s]
Validation DataLoader 0:   3%|▎         | 6/208 [00:02<01:14,  2.71it/s]
Validation DataLoader 0:   3%|▎         | 7/208 [00:02<01:16,  2.64it/s]
Validation DataLoader 0:   4%|▍         | 8/208 [00:03<01:16,  2.63it/s]
Validation DataLoader 0:   4%|▍         | 9/208 [00:03<01:16,  2.60it/s]
Validation DataLoader 0:   5%|▍         | 10/208 [00:03<01:17,  2.56it/s]
Validation DataLoader 0:   5%|▌         | 11/208 [00:04<01:17,  2.54it/s]
Validation DataLoader 0:   6%|▌         | 12/208 [00:04<01:17,  2.53it/s]
Validation DataLoader 0:   6%|▋         | 13/208 [00:05<01:17,  2.51it/s]
Validation DataLoader 0:   7%|▋         | 14/208 [00:05<01:17,  2.49it/s]
Validation DataLoader 0:   7%|▋         | 15/208 [00:06<01:17,  2.49it/s]
Validation DataLoader 0:   8%|▊         | 16/208 [00:06<01:17,  2.48it/s]
Validation DataLoader 0:   8%|▊         | 17/208 [00:06<01:17,  2.48it/s]
Validation DataLoader 0:   9%|▊         | 18/208 [00:07<01:16,  2.47it/s]
Validation DataLoader 0:   9%|▉         | 19/208 [00:07<01:16,  2.47it/s]
Validation DataLoader 0:  10%|▉         | 20/208 [00:08<01:16,  2.47it/s]
Validation DataLoader 0:  10%|█         | 21/208 [00:08<01:15,  2.46it/s]
Validation DataLoader 0:  11%|█         | 22/208 [00:08<01:15,  2.46it/s]
Validation DataLoader 0:  11%|█         | 23/208 [00:09<01:15,  2.46it/s]
Validation DataLoader 0:  12%|█▏        | 24/208 [00:09<01:14,  2.45it/s]
Validation DataLoader 0:  12%|█▏        | 25/208 [00:10<01:14,  2.45it/s]
Validation DataLoader 0:  12%|█▎        | 26/208 [00:10<01:14,  2.45it/s]
Validation DataLoader 0:  13%|█▎        | 27/208 [00:11<01:13,  2.45it/s]
Validation DataLoader 0:  13%|█▎        | 28/208 [00:11<01:13,  2.45it/s]
Validation DataLoader 0:  14%|█▍        | 29/208 [00:11<01:13,  2.44it/s]
Validation DataLoader 0:  14%|█▍        | 30/208 [00:12<01:13,  2.44it/s]
Validation DataLoader 0:  15%|█▍        | 31/208 [00:12<01:12,  2.43it/s]
Validation DataLoader 0:  15%|█▌        | 32/208 [00:13<01:12,  2.44it/s]
Validation DataLoader 0:  16%|█▌        | 33/208 [00:13<01:11,  2.43it/s]
Validation DataLoader 0:  16%|█▋        | 34/208 [00:13<01:11,  2.43it/s]
Validation DataLoader 0:  17%|█▋        | 35/208 [00:14<01:11,  2.43it/s]
Validation DataLoader 0:  17%|█▋        | 36/208 [00:14<01:10,  2.43it/s]
Validation DataLoader 0:  18%|█▊        | 37/208 [00:15<01:10,  2.43it/s]
Validation DataLoader 0:  18%|█▊        | 38/208 [00:15<01:10,  2.43it/s]
Validation DataLoader 0:  19%|█▉        | 39/208 [00:16<01:09,  2.42it/s]
Validation DataLoader 0:  19%|█▉        | 40/208 [00:16<01:10,  2.40it/s]
Validation DataLoader 0:  20%|█▉        | 41/208 [00:17<01:09,  2.40it/s]
Validation DataLoader 0:  20%|██        | 42/208 [00:17<01:09,  2.40it/s]
Validation DataLoader 0:  21%|██        | 43/208 [00:17<01:08,  2.40it/s]
Validation DataLoader 0:  21%|██        | 44/208 [00:18<01:08,  2.40it/s]
Validation DataLoader 0:  22%|██▏       | 45/208 [00:18<01:07,  2.40it/s]
Validation DataLoader 0:  22%|██▏       | 46/208 [00:19<01:07,  2.39it/s]
Validation DataLoader 0:  23%|██▎       | 47/208 [00:19<01:07,  2.39it/s]
Validation DataLoader 0:  23%|██▎       | 48/208 [00:20<01:06,  2.39it/s]
Validation DataLoader 0:  24%|██▎       | 49/208 [00:20<01:06,  2.39it/s]
Validation DataLoader 0:  24%|██▍       | 50/208 [00:20<01:06,  2.39it/s]
Validation DataLoader 0:  25%|██▍       | 51/208 [00:21<01:05,  2.39it/s]
Validation DataLoader 0:  25%|██▌       | 52/208 [00:21<01:05,  2.39it/s]
Validation DataLoader 0:  25%|██▌       | 53/208 [00:22<01:04,  2.39it/s]
Validation DataLoader 0:  26%|██▌       | 54/208 [00:22<01:04,  2.39it/s]
Validation DataLoader 0:  26%|██▋       | 55/208 [00:23<01:04,  2.39it/s]
Validation DataLoader 0:  27%|██▋       | 56/208 [00:23<01:03,  2.39it/s]
Validation DataLoader 0:  27%|██▋       | 57/208 [00:23<01:03,  2.39it/s]
Validation DataLoader 0:  28%|██▊       | 58/208 [00:24<01:02,  2.39it/s]
Validation DataLoader 0:  28%|██▊       | 59/208 [00:24<01:02,  2.39it/s]
Validation DataLoader 0:  29%|██▉       | 60/208 [00:25<01:01,  2.39it/s]
Validation DataLoader 0:  29%|██▉       | 61/208 [00:25<01:01,  2.39it/s]
Validation DataLoader 0:  30%|██▉       | 62/208 [00:25<01:01,  2.39it/s]
Validation DataLoader 0:  30%|███       | 63/208 [00:26<01:00,  2.39it/s]
Validation DataLoader 0:  31%|███       | 64/208 [00:26<01:00,  2.39it/s]
Validation DataLoader 0:  31%|███▏      | 65/208 [00:27<00:59,  2.38it/s]
Validation DataLoader 0:  32%|███▏      | 66/208 [00:27<00:59,  2.38it/s]
Validation DataLoader 0:  32%|███▏      | 67/208 [00:28<00:59,  2.38it/s]
Validation DataLoader 0:  33%|███▎      | 68/208 [00:28<00:58,  2.38it/s]
Validation DataLoader 0:  33%|███▎      | 69/208 [00:28<00:58,  2.38it/s]
Validation DataLoader 0:  34%|███▎      | 70/208 [00:29<00:57,  2.38it/s]
Validation DataLoader 0:  34%|███▍      | 71/208 [00:29<00:57,  2.38it/s]
Validation DataLoader 0:  35%|███▍      | 72/208 [00:30<00:57,  2.38it/s]
Validation DataLoader 0:  35%|███▌      | 73/208 [00:30<00:56,  2.37it/s]
Validation DataLoader 0:  36%|███▌      | 74/208 [00:31<00:56,  2.37it/s]
Validation DataLoader 0:  36%|███▌      | 75/208 [00:31<00:56,  2.37it/s]
Validation DataLoader 0:  37%|███▋      | 76/208 [00:32<00:55,  2.37it/s]
Validation DataLoader 0:  37%|███▋      | 77/208 [00:32<00:55,  2.37it/s]
Validation DataLoader 0:  38%|███▊      | 78/208 [00:32<00:54,  2.37it/s]
Validation DataLoader 0:  38%|███▊      | 79/208 [00:33<00:54,  2.37it/s]
Validation DataLoader 0:  38%|███▊      | 80/208 [00:33<00:54,  2.37it/s]
Validation DataLoader 0:  39%|███▉      | 81/208 [00:34<00:53,  2.37it/s]
Validation DataLoader 0:  39%|███▉      | 82/208 [00:34<00:53,  2.36it/s]
Validation DataLoader 0:  40%|███▉      | 83/208 [00:35<00:52,  2.36it/s]
Validation DataLoader 0:  40%|████      | 84/208 [00:35<00:52,  2.36it/s]
Validation DataLoader 0:  41%|████      | 85/208 [00:36<00:52,  2.36it/s]
Validation DataLoader 0:  41%|████▏     | 86/208 [00:36<00:51,  2.36it/s]
Validation DataLoader 0:  42%|████▏     | 87/208 [00:36<00:51,  2.36it/s]
Validation DataLoader 0:  42%|████▏     | 88/208 [00:37<00:50,  2.35it/s]
Validation DataLoader 0:  43%|████▎     | 89/208 [00:37<00:50,  2.35it/s]
Validation DataLoader 0:  43%|████▎     | 90/208 [00:38<00:50,  2.35it/s]
Validation DataLoader 0:  44%|████▍     | 91/208 [00:38<00:49,  2.35it/s]
Validation DataLoader 0:  44%|████▍     | 92/208 [00:39<00:49,  2.35it/s]
Validation DataLoader 0:  45%|████▍     | 93/208 [00:39<00:48,  2.35it/s]
Validation DataLoader 0:  45%|████▌     | 94/208 [00:40<00:48,  2.35it/s]
Validation DataLoader 0:  46%|████▌     | 95/208 [00:40<00:48,  2.35it/s]
Validation DataLoader 0:  46%|████▌     | 96/208 [00:40<00:47,  2.35it/s]
Validation DataLoader 0:  47%|████▋     | 97/208 [00:41<00:47,  2.35it/s]
Validation DataLoader 0:  47%|████▋     | 98/208 [00:41<00:46,  2.35it/s]
Validation DataLoader 0:  48%|████▊     | 99/208 [00:42<00:46,  2.35it/s]
Validation DataLoader 0:  48%|████▊     | 100/208 [00:42<00:46,  2.35it/s]
Validation DataLoader 0:  49%|████▊     | 101/208 [00:43<00:45,  2.35it/s]
Validation DataLoader 0:  49%|████▉     | 102/208 [00:43<00:45,  2.35it/s]
Validation DataLoader 0:  50%|████▉     | 103/208 [00:43<00:44,  2.35it/s]
Validation DataLoader 0:  50%|█████     | 104/208 [00:44<00:44,  2.35it/s]
Validation DataLoader 0:  50%|█████     | 105/208 [00:44<00:43,  2.35it/s]
Validation DataLoader 0:  51%|█████     | 106/208 [00:45<00:43,  2.35it/s]
Validation DataLoader 0:  51%|█████▏    | 107/208 [00:45<00:43,  2.34it/s]
Validation DataLoader 0:  52%|█████▏    | 108/208 [00:46<00:42,  2.34it/s]
Validation DataLoader 0:  52%|█████▏    | 109/208 [00:46<00:42,  2.34it/s]
Validation DataLoader 0:  53%|█████▎    | 110/208 [00:46<00:41,  2.34it/s]
Validation DataLoader 0:  53%|█████▎    | 111/208 [00:47<00:41,  2.34it/s]
Validation DataLoader 0:  54%|█████▍    | 112/208 [00:47<00:40,  2.34it/s]
Validation DataLoader 0:  54%|█████▍    | 113/208 [00:48<00:40,  2.34it/s]
Validation DataLoader 0:  55%|█████▍    | 114/208 [00:48<00:40,  2.34it/s]
Validation DataLoader 0:  55%|█████▌    | 115/208 [00:49<00:39,  2.34it/s]
Validation DataLoader 0:  56%|█████▌    | 116/208 [00:49<00:39,  2.34it/s]
Validation DataLoader 0:  56%|█████▋    | 117/208 [00:50<00:38,  2.34it/s]
Validation DataLoader 0:  57%|█████▋    | 118/208 [00:50<00:38,  2.34it/s]
Validation DataLoader 0:  57%|█████▋    | 119/208 [00:50<00:38,  2.34it/s]
Validation DataLoader 0:  58%|█████▊    | 120/208 [00:51<00:37,  2.34it/s]
Validation DataLoader 0:  58%|█████▊    | 121/208 [00:51<00:37,  2.34it/s]
Validation DataLoader 0:  59%|█████▊    | 122/208 [00:52<00:36,  2.34it/s]
Validation DataLoader 0:  59%|█████▉    | 123/208 [00:52<00:36,  2.34it/s]
Validation DataLoader 0:  60%|█████▉    | 124/208 [00:53<00:35,  2.34it/s]
Validation DataLoader 0:  60%|██████    | 125/208 [00:53<00:35,  2.34it/s]
Validation DataLoader 0:  61%|██████    | 126/208 [00:53<00:35,  2.34it/s]
Validation DataLoader 0:  61%|██████    | 127/208 [00:54<00:34,  2.34it/s]
Validation DataLoader 0:  62%|██████▏   | 128/208 [00:54<00:34,  2.34it/s]
Validation DataLoader 0:  62%|██████▏   | 129/208 [00:55<00:33,  2.34it/s]
Validation DataLoader 0:  62%|██████▎   | 130/208 [00:55<00:33,  2.34it/s]
Validation DataLoader 0:  63%|██████▎   | 131/208 [00:56<00:32,  2.34it/s]
Validation DataLoader 0:  63%|██████▎   | 132/208 [00:56<00:32,  2.34it/s]
Validation DataLoader 0:  64%|██████▍   | 133/208 [00:56<00:32,  2.34it/s]
Validation DataLoader 0:  64%|██████▍   | 134/208 [00:57<00:31,  2.34it/s]
Validation DataLoader 0:  65%|██████▍   | 135/208 [00:57<00:31,  2.34it/s]
Validation DataLoader 0:  65%|██████▌   | 136/208 [00:58<00:30,  2.34it/s]
Validation DataLoader 0:  66%|██████▌   | 137/208 [00:58<00:30,  2.34it/s]
Validation DataLoader 0:  66%|██████▋   | 138/208 [00:59<00:29,  2.34it/s]
Validation DataLoader 0:  67%|██████▋   | 139/208 [00:59<00:29,  2.34it/s]
Validation DataLoader 0:  67%|██████▋   | 140/208 [00:59<00:29,  2.34it/s]
Validation DataLoader 0:  68%|██████▊   | 141/208 [01:00<00:28,  2.34it/s]
Validation DataLoader 0:  68%|██████▊   | 142/208 [01:00<00:28,  2.34it/s]
Validation DataLoader 0:  69%|██████▉   | 143/208 [01:01<00:27,  2.34it/s]
Validation DataLoader 0:  69%|██████▉   | 144/208 [01:01<00:27,  2.34it/s]
Validation DataLoader 0:  70%|██████▉   | 145/208 [01:01<00:26,  2.34it/s]
Validation DataLoader 0:  70%|███████   | 146/208 [01:02<00:26,  2.34it/s]
Validation DataLoader 0:  71%|███████   | 147/208 [01:02<00:26,  2.34it/s]
Validation DataLoader 0:  71%|███████   | 148/208 [01:03<00:25,  2.34it/s]
Validation DataLoader 0:  72%|███████▏  | 149/208 [01:03<00:25,  2.34it/s]
Validation DataLoader 0:  72%|███████▏  | 150/208 [01:04<00:24,  2.34it/s]
Validation DataLoader 0:  73%|███████▎  | 151/208 [01:04<00:24,  2.34it/s]
Validation DataLoader 0:  73%|███████▎  | 152/208 [01:04<00:23,  2.34it/s]
Validation DataLoader 0:  74%|███████▎  | 153/208 [01:05<00:23,  2.34it/s]
Validation DataLoader 0:  74%|███████▍  | 154/208 [01:05<00:23,  2.34it/s]
Validation DataLoader 0:  75%|███████▍  | 155/208 [01:06<00:22,  2.34it/s]
Validation DataLoader 0:  75%|███████▌  | 156/208 [01:06<00:22,  2.34it/s]
Validation DataLoader 0:  75%|███████▌  | 157/208 [01:06<00:21,  2.34it/s]
Validation DataLoader 0:  76%|███████▌  | 158/208 [01:07<00:21,  2.34it/s]
Validation DataLoader 0:  76%|███████▋  | 159/208 [01:07<00:20,  2.34it/s]
Validation DataLoader 0:  77%|███████▋  | 160/208 [01:08<00:20,  2.35it/s]
Validation DataLoader 0:  77%|███████▋  | 161/208 [01:08<00:20,  2.35it/s]
Validation DataLoader 0:  78%|███████▊  | 162/208 [01:09<00:19,  2.35it/s]
Validation DataLoader 0:  78%|███████▊  | 163/208 [01:09<00:19,  2.35it/s]
Validation DataLoader 0:  79%|███████▉  | 164/208 [01:09<00:18,  2.35it/s]
Validation DataLoader 0:  79%|███████▉  | 165/208 [01:10<00:18,  2.35it/s]
Validation DataLoader 0:  80%|███████▉  | 166/208 [01:10<00:17,  2.35it/s]
Validation DataLoader 0:  80%|████████  | 167/208 [01:11<00:17,  2.35it/s]
Validation DataLoader 0:  81%|████████  | 168/208 [01:11<00:17,  2.35it/s]
Validation DataLoader 0:  81%|████████▏ | 169/208 [01:12<00:16,  2.35it/s]
Validation DataLoader 0:  82%|████████▏ | 170/208 [01:12<00:16,  2.35it/s]
Validation DataLoader 0:  82%|████████▏ | 171/208 [01:12<00:15,  2.35it/s]
Validation DataLoader 0:  83%|████████▎ | 172/208 [01:13<00:15,  2.35it/s]
Validation DataLoader 0:  83%|████████▎ | 173/208 [01:13<00:14,  2.35it/s]
Validation DataLoader 0:  84%|████████▎ | 174/208 [01:14<00:14,  2.35it/s]
Validation DataLoader 0:  84%|████████▍ | 175/208 [01:14<00:14,  2.35it/s]
Validation DataLoader 0:  85%|████████▍ | 176/208 [01:14<00:13,  2.35it/s]
Validation DataLoader 0:  85%|████████▌ | 177/208 [01:15<00:13,  2.35it/s]
Validation DataLoader 0:  86%|████████▌ | 178/208 [01:15<00:12,  2.35it/s]
Validation DataLoader 0:  86%|████████▌ | 179/208 [01:16<00:12,  2.35it/s]
Validation DataLoader 0:  87%|████████▋ | 180/208 [01:16<00:11,  2.35it/s]
Validation DataLoader 0:  87%|████████▋ | 181/208 [01:17<00:11,  2.35it/s]
Validation DataLoader 0:  88%|████████▊ | 182/208 [01:17<00:11,  2.35it/s]
Validation DataLoader 0:  88%|████████▊ | 183/208 [01:17<00:10,  2.35it/s]
Validation DataLoader 0:  88%|████████▊ | 184/208 [01:18<00:10,  2.35it/s]
Validation DataLoader 0:  89%|████████▉ | 185/208 [01:18<00:09,  2.35it/s]
Validation DataLoader 0:  89%|████████▉ | 186/208 [01:19<00:09,  2.35it/s]
Validation DataLoader 0:  90%|████████▉ | 187/208 [01:19<00:08,  2.35it/s]
Validation DataLoader 0:  90%|█████████ | 188/208 [01:20<00:08,  2.35it/s]
Validation DataLoader 0:  91%|█████████ | 189/208 [01:20<00:08,  2.35it/s]
Validation DataLoader 0:  91%|█████████▏| 190/208 [01:20<00:07,  2.35it/s]
Validation DataLoader 0:  92%|█████████▏| 191/208 [01:21<00:07,  2.35it/s]
Validation DataLoader 0:  92%|█████████▏| 192/208 [01:21<00:06,  2.35it/s]
Validation DataLoader 0:  93%|█████████▎| 193/208 [01:22<00:06,  2.35it/s]
Validation DataLoader 0:  93%|█████████▎| 194/208 [01:22<00:05,  2.35it/s]
Validation DataLoader 0:  94%|█████████▍| 195/208 [01:23<00:05,  2.35it/s]
Validation DataLoader 0:  94%|█████████▍| 196/208 [01:23<00:05,  2.35it/s]
Validation DataLoader 0:  95%|█████████▍| 197/208 [01:23<00:04,  2.35it/s]
Validation DataLoader 0:  95%|█████████▌| 198/208 [01:24<00:04,  2.35it/s]
Validation DataLoader 0:  96%|█████████▌| 199/208 [01:24<00:03,  2.35it/s]
Validation DataLoader 0:  96%|█████████▌| 200/208 [01:25<00:03,  2.35it/s]
Validation DataLoader 0:  97%|█████████▋| 201/208 [01:25<00:02,  2.35it/s]
Validation DataLoader 0:  97%|█████████▋| 202/208 [01:26<00:02,  2.35it/s]
Validation DataLoader 0:  98%|█████████▊| 203/208 [01:26<00:02,  2.35it/s]

     targets    prob_0    prob_1
0       1.0  0.652880  0.347120
1       0.0  0.624135  0.375865
2       0.0  0.680962  0.319038
3       0.0  0.738293  0.261707
4       0.0  0.608293  0.391707
5       1.0  0.514038  0.485962
6       1.0  0.498399  0.501601
7       0.0  0.620988  0.379012
8       0.0  0.653664  0.346336
9       0.0  0.563649  0.436351
10      1.0  0.651613  0.348387
11      0.0  0.789985  0.210015
12      0.0  0.839461  0.160539
13      0.0  0.883419  0.116581
14      0.0  0.667050  0.332950
15      1.0  0.371101  0.628899
16      1.0  0.702376  0.297624
17      0.0  0.768811  0.231189
18      0.0  0.747977  0.252023
19      0.0  0.651947  0.348053



Epoch 32: 100%|██████████| 1195/1195 [17:56<00:00,  1.11it/s, v_num=4, train_acc_mz_bin=0.121, val_acc_mz_bin=0.112, retrain_val_auc=0.868, retrain_val_ap=0.872]Probe epoch 0 loss: 0.7974  auc: 0.4960  ap: 0.5980
Probe epoch 1 loss: 0.8817  auc: 0.5754  ap: 0.5992
Probe epoch 2 loss: 0.8292  auc: 0.7183  ap: 0.7618
Probe epoch 3 loss: 0.6309  auc: 0.7222  ap: 0.7671
Probe epoch 4 loss: 0.6417  auc: 0.6845  ap: 0.7290
Probe epoch 5 loss: 0.7145  auc: 0.6865  ap: 0.7397
Probe epoch 6 loss: 0.6320  auc: 0.7302  ap: 0.7686
Probe epoch 7 loss: 0.5540  auc: 0.7698  ap: 0.7978
Probe epoch 8 loss: 0.5727  auc: 0.8254  ap: 0.8385
Probe epoch 9 loss: 0.6058  auc: 0.8532  ap: 0.8576
Probe epoch 10 loss: 0.5902  auc: 0.8571  ap: 0.8637
Probe epoch 11 loss: 0.5412  auc: 0.8651  ap: 0.8695
Probe epoch 12 loss: 0.5081  auc: 0.8690  ap: 0.8731
Probe epoch 13 loss: 0.5177  auc: 0.8690  ap: 0.8735
Probe epoch 14 loss: 0.5351  auc: 0.8730  ap: 0.8773
Probe epoch 15 loss: 0.5197  auc: 0.8730  ap: 0.8822
Probe epoch 16 loss: 0.4875  auc: 0.8810  ap: 0.8934
Probe epoch 17 loss: 0.4740  auc: 0.8810  ap: 0.8934
Probe epoch 18 loss: 0.4812  auc: 0.8810  ap: 0.8934
Probe epoch 19 loss: 0.4866  auc: 0.8889  ap: 0.9020
Probe epoch 20 loss: 0.4768  auc: 0.8889  ap: 0.9020
Probe epoch 21 loss: 0.4583  auc: 0.8968  ap: 0.9124
Probe epoch 22 loss: 0.4470  auc: 0.9008  ap: 0.9171
Probe epoch 23 loss: 0.4488  auc: 0.9008  ap: 0.9171
Probe epoch 24 loss: 0.4520  auc: 0.9008  ap: 0.9171
Probe epoch 25 loss: 0.4445  auc: 0.9008  ap: 0.9171
Probe epoch 26 loss: 0.4311  auc: 0.9048  ap: 0.9197
Probe epoch 27 loss: 0.4235  auc: 0.9087  ap: 0.9238
Probe epoch 28 loss: 0.4232  auc: 0.9167  ap: 0.9309
Probe epoch 29 loss: 0.4226  auc: 0.9206  ap: 0.9341
Probe epoch 30 loss: 0.4162  auc: 0.9206  ap: 0.9341
Probe epoch 31 loss: 0.4065  auc: 0.9206  ap: 0.9341
Probe epoch 32 loss: 0.3999  auc: 0.9286  ap: 0.9402
Probe epoch 33 loss: 0.3982  auc: 0.9325  ap: 0.9429
Probe epoch 34 loss: 0.3963  auc: 0.9444  ap: 0.9515
Probe epoch 35 loss: 0.3903  auc: 0.9444  ap: 0.9515
Probe epoch 36 loss: 0.3828  auc: 0.9524  ap: 0.9574
Probe epoch 37 loss: 0.3781  auc: 0.9563  ap: 0.9603
Probe epoch 38 loss: 0.3759  auc: 0.9603  ap: 0.9633
Probe epoch 39 loss: 0.3728  auc: 0.9603  ap: 0.9633
Probe epoch 40 loss: 0.3673  auc: 0.9603  ap: 0.9633
Probe epoch 41 loss: 0.3614  auc: 0.9603  ap: 0.9633
Probe epoch 42 loss: 0.3575  auc: 0.9643  ap: 0.9664
Probe epoch 43 loss: 0.3549  auc: 0.9643  ap: 0.9664
Probe epoch 44 loss: 0.3511  auc: 0.9762  ap: 0.9765
Probe epoch 45 loss: 0.3460  auc: 0.9762  ap: 0.9765
Probe epoch 46 loss: 0.3414  auc: 0.9762  ap: 0.9765
Probe epoch 47 loss: 0.3380  auc: 0.9762  ap: 0.9765
Probe epoch 48 loss: 0.3350  auc: 0.9762  ap: 0.9765
Probe epoch 49 loss: 0.3310  auc: 0.9841  ap: 0.9849
Epoch 33: 100%|██████████| 1195/1195 [16:13<00:00,  1.23it/s, v_num=4, train_acc_mz_bin=0.109, val_acc_mz_bin=0.112, retrain_val_auc=0.868, retrain_val_ap=0.872]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation:   0%|          | 0/208 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/208 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 1/208 [00:00<00:25,  8.21it/s]
Validation DataLoader 0:   1%|          | 2/208 [00:00<00:54,  3.75it/s]
Validation DataLoader 0:   1%|▏         | 3/208 [00:00<01:06,  3.10it/s]
Validation DataLoader 0:   2%|▏         | 4/208 [00:01<01:10,  2.88it/s]
Validation DataLoader 0:   2%|▏         | 5/208 [00:01<01:14,  2.72it/s]
Validation DataLoader 0:   3%|▎         | 6/208 [00:02<01:16,  2.65it/s]
Validation DataLoader 0:   3%|▎         | 7/208 [00:02<01:17,  2.61it/s]
Validation DataLoader 0:   4%|▍         | 8/208 [00:03<01:17,  2.58it/s]
Validation DataLoader 0:   4%|▍         | 9/208 [00:03<01:18,  2.53it/s]
Validation DataLoader 0:   5%|▍         | 10/208 [00:03<01:18,  2.51it/s]
Validation DataLoader 0:   5%|▌         | 11/208 [00:04<01:18,  2.50it/s]
Validation DataLoader 0:   6%|▌         | 12/208 [00:04<01:18,  2.49it/s]
Validation DataLoader 0:   6%|▋         | 13/208 [00:05<01:18,  2.48it/s]

Detected KeyboardInterrupt, attempting graceful shutdown ...

NameError: name 'exit' is not defined

In [ ]:
# Can it be that end_validation_epoch happens before end_train_epoch? why?

In [ ]:
# - to build learning curves (later)
    # - several experiments with multiple datasets of various sizes
    # - we can either train for a fixed number of epochs, or steps
    # (probably, steps would be better)